apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: emanelsayed/udagram-reverseproxy:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080