apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    service: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-user
  template:
    metadata:
      labels:
        service: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: emanelsayed/udagram-api-user:v1.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: env-configmap